# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
